// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCZczSJY0WUwjk084EjBcA5HqdEKGXt8Ig',
    appId: '1:1035951042202:web:da129170e70e6acc777923',
    messagingSenderId: '1035951042202',
    projectId: 'instaflutter-444aa',
    authDomain: 'instaflutter-444aa.firebaseapp.com',
    storageBucket: 'instaflutter-444aa.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCZHzmlMYSN6FtoUOhlU12sECTu_6IZNYc',
    appId: '1:1035951042202:android:b46bf6f95b2ac272777923',
    messagingSenderId: '1035951042202',
    projectId: 'instaflutter-444aa',
    storageBucket: 'instaflutter-444aa.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCo0OyW1_l_Rz4xbPkwAdRU6zpbhypQlfo',
    appId: '1:1035951042202:ios:e94b393873b172ee777923',
    messagingSenderId: '1035951042202',
    projectId: 'instaflutter-444aa',
    storageBucket: 'instaflutter-444aa.appspot.com',
    iosBundleId: 'com.example.instaFlut',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCo0OyW1_l_Rz4xbPkwAdRU6zpbhypQlfo',
    appId: '1:1035951042202:ios:a5b606c28deb32a4777923',
    messagingSenderId: '1035951042202',
    projectId: 'instaflutter-444aa',
    storageBucket: 'instaflutter-444aa.appspot.com',
    iosBundleId: 'com.example.instaFlut.RunnerTests',
  );
}
